### ISSUE TITLE
Crashes when pressing 'o' while focused on a message

### ISSUE THREAD

**Issue by binlaab** [rigormorrtiss/discordo#140]
Whenever I press the 'o' key while I'm focused on a message, the program exits with the following output:
```
panic: runtime error: index out of range [-1] [recovered]
        panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
        github.com/rivo/tview@v0.0.0-20220216162559-96063d6082f3/application.go:243 +0x4d
panic({0x561b3e031740, 0xc0009a8438})
        runtime/panic.go:1038 +0x215
github.com/ayntgl/discordo/ui.(*MessagesTextView).onInputCapture(0xc000021480, 0xc000109c80)
        github.com/ayntgl/discordo/ui/messages.go:100 +0xea5
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc000021480, 0xc000109cd8)
        github.com/rivo/tview@v0.0.0-20220216162559-96063d6082f3/box.go:164 +0x3a
github.com/rivo/tview.(*Flex).InputHandler.func1(0xc000109d18, 0x561b3dd5cf3f)
        github.com/rivo/tview@v0.0.0-20220216162559-96063d6082f3/flex.go:251 +0xd9
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc000633ad0, 0x10)
        github.com/rivo/tview@v0.0.0-20220216162559-96063d6082f3/box.go:167 +0x53
github.com/rivo/tview.(*Flex).InputHandler.func1(0x561b3da729a7, 0x10)
        github.com/rivo/tview@v0.0.0-20220216162559-96063d6082f3/flex.go:251 +0xd9
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc00007b950, 0xc000109e20)
        github.com/rivo/tview@v0.0.0-20220216162559-96063d6082f3/box.go:167 +0x53
github.com/rivo/tview.(*Application).Run(0xc0001b4460)
        github.com/rivo/tview@v0.0.0-20220216162559-96063d6082f3/application.go:335 +0x886
main.main()
        github.com/ayntgl/discordo/main.go:103 +0x2a7
```
I'm using kitty in Debian 11, if that helps.

**Comment by KodiCraft** [comment]
Does this occur when you navigate through messages with the keyboard keys or while using the mouse?

**Comment by ghost** [comment]
Fixed
