### ISSUE TITLE
Doesn't work with zsh [panic: websocket: close 4004: Authentication failed.]

### ISSUE THREAD

**Issue by Ryuo1** [rigormorrtiss/discordo#160]
```
panic: websocket: close 4004: Authentication failed.

goroutine 1 [running]:
main.main.func1(0xc0000aa1c0?)
        /home/ryuo/.cache/paru/clone/discordo-git/src/discordo/main.go:56 +0x334
github.com/urfave/cli/v2.(*App).RunContext(0xc00008a680, {0x9fb228?, 0xc000024200}, {0xc000020180, 0x3, 0x3})
        /home/ryuo/go/pkg/mod/github.com/urfave/cli/v2@v2.7.1/app.go:329 +0x9d3
github.com/urfave/cli/v2.(*App).Run(...)
        /home/ryuo/go/pkg/mod/github.com/urfave/cli/v2@v2.7.1/app.go:226
main.main()
        /home/ryuo/.cache/paru/clone/discordo-git/src/discordo/main.go:143 +0x2f0
```

**Comment by Ryuo1** [comment]
discordo starts normally from bash. But when I launch from zsh, I get the above error.

**Comment by sozoalvin** [comment]
curious: why should using zsh/ different shell affect if the binary runs or not?

**Comment by Ryuo1** [comment]
I don't know. My hard drive corrupted, and I can't do anything now.
